### ISSUE TITLE
CUB_resnet_baseline? 

### ISSUE THREAD

**Issue by collinskatie** [princetonvisualai/OverlookedFactors#1]
Thank you for your awesome + inspiring paper, and for releasing the code! 

I am particularly interested in the code in the ConceptLearning notebook and couldn't seem to find where "CUB_resnet_baseline" is derived from in the codebase? Apologies if I missed something here! 

Thanks for any clarification on where I may find "CUB_resnet_baseline" and/or best replicate that portion. Thanks!

**Comment by vramaswamy94** [comment]
Whoops, sorry. That's the folder where we stored the train/val/test split for the CUB dataset as well as the predictions of the blackbox (or Concept Bottleneck) model trained on CUB
